In [1]:
import numpy as np

**Valid Sudoku**

In [4]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [6]:
print(np.sum(s, axis=1))

[45 45 45 45 45 45 45 45 45]


In [7]:
print(np.sum(s, axis=0))

[45 45 45 45 45 45 45 45 45]


In [15]:
for i in range(0,9,3):
    for j in range(0,9,3):
        if s[i:i+3,j:j+3].sum() !=45:
            print("NOT a valid sudoku")
            break
else:
    print("VALID SUDOKU")

VALID SUDOKU


demo

**General Questions**

In [1]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [2]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [7]:
#Find the average age of students.
print(np.mean(data[:,0]))

18.4


In [8]:
#Extract Math marks of all students.
print(data[ : ,1])

[85 92 76 65 90]


In [9]:
#Find the highest Science mark.
print(np.max(data[ : ,2]))

95


In [11]:
#Get details of the student who scored more than 90 in Math.
print(data[data[ : ,1]>90])

[[19 92 88]]


In [12]:
#Increase Math marks of all students by 5.
data[ : ,1]+=5
print(data)

[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]


In [14]:
#Find how many students are younger than 19.
print(len(data[data[ : ,0]<19]))

3


In [17]:
#Calculate the average marks in each subject (column-wise mean).
slice=data[ : ,1:]
column_wise_mean=np.mean(slice, axis=0)
print(column_wise_mean)

[86.6 83.2]


In [21]:
#Get data of students who scored at least 80 in both subjects.
print(data[(data[:,1]>=80) & (data[:,2]>=80)])

[[19 97 88]
 [17 81 95]
 [20 95 85]]


In [25]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75]=0
print(data)

[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70  0]
 [20 95 85]]
